import re

with open("Project/ai_service/generate_optimized_dataset.py", "r") as f:
    text = f.read()

# Replace Spanish strings and comments with corresponding English strings
replacements = {
    "Generador de Dataset Optimizado para HCT Survival": "Optimized Dataset Generator for HCT Survival",
    "Basado en las recomendaciones de optimización:": "Based on optimization recommendations:",
    "ELIMINAR variables redundantes y con fuga": "REMOVE redundant and leaked variables",
    "MANTENER las top predictors": "KEEP top predictors",
    "CREAR nuevas features que REEMPLAZAN las originales": "CREATE new features that REPLACE original ones",
    "Entrada:": "Input:",
    "Salida:": "Output:",
    "GENERACIÓN DE DATASET OPTIMIZADO": "OPTIMIZED DATASET GENERATION",
    "CARGAR DATOS": "LOAD DATA",
    "Datos cargados:": "Data loaded:",
    "filas": "rows",
    "columnas": "columns",
    "Guardar targets y metadata antes de transformar": "Save targets and metadata before transforming",
    "Contar features originales": "Count original features",
    "DEFINIR QUÉ SE ELIMINA, QUÉ SE CREA, QUÉ SE REEMPLAZA": "DEFINE WHAT IS REMOVED, CREATED, REPLACED",
    "PASO 1: Eliminación directa (redundancia / fuga)": "STEP 1: Direct removal (redundancy / leakage)",
    "Fuga de datos": "Data leakage",
    "redundante con HLA agregadas": "redundant with aggregated HLAs",
    "capturada por comorbidity_score": "captured by comorbidity_score",
    "capturada por age_at_hct + donor_related": "captured by age_at_hct + donor_related",
    "Variables HLA individuales → reemplazadas por hla_composite": "Individual HLA variables -> replaced by hla_composite",
    "Una vez creada, las individuales de locus sobran": "Once created, locus individual ones are redundant",
    "entra en el cálculo del composite": "enters composite calculation",
    "individual → capturada por composite": "individual -> captured by composite",
    "agregada baja res → capturada por composite": "aggregated low res -> captured by composite",
    "Categóricas reemplazadas por sus encodings ordinales": "Categoricals replaced by their ordinal encodings",
    "Las categóricas originales ya no son necesarias": "Original categoricals are no longer needed",
    "Comorbilidades individuales → reemplazadas por n_comorbidities + risk": "Individual comorbidities -> replaced by n_comorbidities + risk",
    "Se mantiene comorbidity_score (Sorror) como numérica, pero las 13": "Keep comorbidity_score (Sorror) as numerical, but the 13",
    "banderas individuales se consolidan en n_comorbidities + n_comorbidities_risk": "individual flags consolidate into n_comorbidities + n_comorbidities_risk",
    "graft_type y prod_type son redundantes entre sí": "graft_type and prod_type are mutually redundant",
    "duplicado de graft_type": "duplicate of graft_type",
    "Total a eliminar": "Total to remove",
    "FEATURE ENGINEERING (crear ANTES de eliminar, porque usamos las originales)": "FEATURE ENGINEERING (create BEFORE deleting, since we use the originals)",
    "PASO 1: CREAR NUEVAS FEATURES": "STEP 1: CREATE NEW FEATURES",
    "Crea features con respaldo clínico. Usa las columnas originales": "Creates features with clinical backing. Uses the original columns",
    "para calcular, luego se eliminan las originales.": "to calculate, then the originals are removed.",
    "A) hla_composite: Carga Genética Total": "A) hla_composite: Total Genetic Load",
    "media": "mean",
    "REEMPLAZA": "REPLACES",
    "variables HLA individuales": "individual HLA variables",
    "B) age_x_comorbidity: El Choque Físico": "B) age_x_comorbidity: Physical Shock",
    "C) dri_x_conditioning: El Balance del Tratamiento": "C) dri_x_conditioning: Treatment Balance",
    "REEMPLAZAN": "REPLACE",
    "categóricas": "categoricals",
    "D) missing_count: Vulnerabilidad/Acceso": "D) missing_count: Vulnerability/Access",
    "conteo de NaN + 'Not done' por paciente": "NaN + 'Not done' count per patient",
    "conteo de": "count of",
    "comorbilidades": "comorbidities",
    "banderas individuales": "individual flags",
    "obesidad": "obesity",
    "ELIMINAR LAS ORIGINALES QUE FUERON REEMPLAZADAS": "REMOVE ORIGINALS THAT WERE REPLACED",
    "PASO 2: ELIMINAR VARIABLES REEMPLAZADAS": "STEP 2: REMOVE REPLACED VARIABLES",
    "Eliminando de Train:": "Removing from Train:",
    "Eliminando de Test:": "Removing from Test:",
    "Detalle de eliminaciones:": "Removal details:",
    "fuga/redundancia directa": "leakage/direct redundancy",
    "reemplazada por encoding ordinal": "replaced by ordinal encoding",
    "reemplazada por n_comorbidities": "replaced by n_comorbidities",
    "duplicado": "duplicate",
    "otro": "other",
    "RE-AGREGAR TARGETS AL TRAIN": "RE-ADD TARGETS TO TRAIN",
    "RESUMEN Y VERIFICACIÓN": "SUMMARY AND VERIFICATION",
    "RESUMEN FINAL": "FINAL SUMMARY",
    "Variables originales (features):": "Original variables (features):",
    "Eliminadas": "Removed",
    "Mantenidas sin cambio": "Maintained without changes",
    "Creadas (reemplazo)": "Created (replacement)",
    "Variables finales (features)": "Final variables (features)",
    "Reducción neta": "Net reduction",
    "menos": "less",
    "Variables MANTENIDAS": "Variables KEPT",
    "Variables CREADAS": "Variables CREATED",
    "Train final:": "Final Train:",
    "Test final:": "Final Test:",
    "Verificación: las nuevas features no deben ser constantes": "Verification: new features should not be constant",
    "VERIFICACIÓN DE NUEVAS FEATURES": "NEW FEATURES VERIFICATION",
    "ALERTA": "ALERT",
    "es CONSTANTE — revisar lógica": "is CONSTANT — check logic",
    "GUARDAR": "SAVE",
    "Archivos guardados:": "Files saved:",
    "Dataset optimizado:": "Optimized dataset:"
}

for k, v in replacements.items():
    text = text.replace(k, v)

with open("Project/ai_service/generate_optimized_dataset.py", "w") as f:
    f.write(text)

